### ISSUE TITLE
File not found random occurences for ricebowl.txt

### ISSUE THREAD

**Issue by srohan19** [rohanpls/shellgreeter#1]
It's very rare but sometimes there's a file not found error for ricebowl.txt

**Comment by rohanpls** [comment]
Added a permanent fix: d2c7b44f7e4c5ba17edea6408be772ab88158ae5

**Comment by srohan19** [comment]
Added a permanent fix: d2c7b44f7e4c5ba17edea6408be772ab88158ae5
